name: Building and Testing Deployment Over Dynatrace 
on:
  push:
    branches:
      - main

jobs:
  Dynatrace_Data_Forwarding : # clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Build count
        uses: dynatrace-oss/dynatrace-github-action@v8
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          metrics: |
            - metric: "apisero-github-success"
              value: "1.0"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: prashant-demo110    
